# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xN3gkDvosj3MUu74LuTAf1KwT2qe2ih
"""

import hashlib
hash_object = hashlib.sha224(b'Hello World')
hash_object = hashlib.sha256(b'Hello World')
hash_object = hashlib.sha384(b'Hello World')
hex_dig = hash_object.hexdigest()
print(hex_dig)


