# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xN3gkDvosj3MUu74LuTAf1KwT2qe2ih
"""

import hashlib

def md5():
        a="basil"
        b=a.encode()
        c=hashlib.md5(b)
        hexa=c.hexdigest()
        print (hexa)
        var hashlib = sha512(salt + password); 
for (i = 0; i < 1000; i++) {
    hashlib = sha512(hashlib); 
}
        return

md5()